Habit Tracker project
TheCSharpAcademy/CodeReviews.Console.HabitTracker pull request #19
Opened 2023-04-21 22:29 UTC by JsPeanut

2023-04-24 02:20 UTC, TheCSharpAcademy commented
@JsPeanut HI there! Just checking if you have submitted the project in the website? I can't see it in our database.

2023-04-24 09:07 UTC, JsPeanut commented
No I haven't. My bad. Will submit it as soon as I get home.

2023-04-26 19:19 UTC, JsPeanut commented
I just submitted! Sorry for the delay.

2023-05-03 23:51 UTC, TheCSharpAcademy requested changes
Hi! The project looks great, well done! 

All the comments are in regards to code tidiness. Usually I don't mind these in the initial projects, but since is your third, I'll be enforcing our code conventions, which can be found here: http://thecsharpacademy.com/article/58

2023-05-03 23:51 UTC, TheCSharpAcademy commented on HabitTracker.JsPeanut/HabitTracker.JsPeanut/Program.cs
> +using System.Text.RegularExpressions;
Please remove unused using

2023-05-03 23:51 UTC, TheCSharpAcademy commented on HabitTracker.JsPeanut/HabitTracker.JsPeanut/Program.cs
> +
Please remove unnecessary empty line 27

2023-05-03 23:51 UTC, TheCSharpAcademy commented on HabitTracker.JsPeanut/HabitTracker.JsPeanut/Program.cs
> +
Please remove unnecessary empty lines 212, 213

2023-05-03 23:51 UTC, TheCSharpAcademy commented on HabitTracker.JsPeanut/HabitTracker.JsPeanut/Program.cs
> +
Please remove unnecessary empty line 285

2023-05-03 23:51 UTC, TheCSharpAcademy commented on HabitTracker.JsPeanut/HabitTracker.JsPeanut/Program.cs
> +
Please remove unnecessary empty line 386

2023-05-03 23:51 UTC, TheCSharpAcademy commented on HabitTracker.JsPeanut/HabitTracker.JsPeanut/Program.cs
> +            public int Id { get; set; }
For consistency, either have one empty line between properties, or none.

2023-05-16 00:54 UTC, TheCSharpAcademy commented
@JsPeanut let me know if you need help! 😁

2023-05-21 19:32 UTC, JsPeanut commented
sorry man! i was too busy trying to finish the coding tracker project that i forgot this one. done

2023-05-22 04:24 UTC, merged