Habit-Tracker-JVR-Hannes
TheCSharpAcademy/CodeReviews.Console.HabitTracker pull request #199
Opened 2024-09-08 08:31 UTC by JvR-Hannes

2024-09-12 15:25 UTC, chrisjamiecarter commented
Hey @JvR-Hannes 👋 ,

Just a quick one before I begin looking at your code.

When you submit a project, remember to submit the correct url
 - https://github.com/TheCSharpAcademy/CodeReviews.Console.HabitTracker/pull/199

When viewing the pull request from the Academy, it links to the project repo 😄 
- https://github.com/TheCSharpAcademy/CodeReviews.Console.HabitTracker

So I had to do some detective work to link them 🕵️ ...

Thanks
@chrisjamiecarter

2024-09-12 15:31 UTC, chrisjamiecarter requested changes
Hey @JvR-Hannes,

Well done on another project submission 🎉 

Unfortunately, you have forgotten to meet one [requirement](https://thecsharpacademy.com/project/12/habit-logger).

- [x] Your project needs to contain a Read Me file where you'll explain how your app works.

Please add a README file as per requirements 😄 .

Thanks
@chrisjamiecarter

2024-09-12 16:47 UTC, JvR-Hannes commented
Hi Chris,

My sincerest apologies about that. I felt like somewhere I missed something
or missed a step.

Thank you for informing me, I will look into it and try not to do it in the
future again.

Thanks you Chris.

Regards

On Thu, 12 Sept 2024, 17:31 Chris Carter, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hey @JvR-Hannes <https://github.com/JvR-Hannes>,
>
> Well done on another project submission 🎉
>
> Unfortunately, you have forgotten to meet one requirement
> <https://thecsharpacademy.com/project/12/habit-logger>.
>
>    - Your project needs to contain a Read Me file where you'll explain
>    how your app works.
>
> Please add a README file as per requirements 😄 .
>
> Thanks
> @chrisjamiecarter <https://github.com/chrisjamiecarter>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/TheCSharpAcademy/CodeReviews.Console.HabitTracker/pull/199#pullrequestreview-2300708683>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A62U75RZISO35JOR3IMCJP3ZWGXVDAVCNFSM6AAAAABN2Y4CDSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGMBQG4YDQNRYGM>
> .
> You are receiving this because you were mentioned.Message ID:
> <TheCSharpAcademy/CodeReviews.Console.
> ***@***.***>
>

2024-09-13 05:50 UTC, JvR-Hannes commented
Hi Chris

Is it possible to change the name locally and push it or will it affect my
app?

Thanks

On Thu, 12 Sept 2024, 21:43 Chris Carter, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> @JvR-Hannes <https://github.com/JvR-Hannes>,
>
> Well done on a great README file!
>
> One more thing before I can continue.
>
> Could you rename the directory to HabitTracker.JvR-Hannes as per the
> code-reviews <https://thecsharpacademy.com/article/52/code-reviews> page,
> and ensure that everything is contained within this folder (i.e. the readme
> you just created):
>
> image.png (view on web)
> <https://github.com/user-attachments/assets/32dca507-df4c-47fd-87cb-a365e08a2d2e>
>
> The reason for this is otherwise files you have added could conflict the
> existing codebase. This will be important on the later projects.
>
> Thanks
> @chrisjamiecarter <https://github.com/chrisjamiecarter>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/TheCSharpAcademy/CodeReviews.Console.HabitTracker/pull/199#pullrequestreview-2301268935>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A62U75U5NLMYTJ76XYEFW4LZWHVGRAVCNFSM6AAAAABN2Y4CDSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGMBRGI3DQOJTGU>
> .
> You are receiving this because you were mentioned.Message ID:
> <TheCSharpAcademy/CodeReviews.Console.
> ***@***.***>
>

2024-09-13 08:46 UTC, chrisjamiecarter commented
@JvR-Hannes Yes make you changes locally, commit, then push to update this PR.

Any issues let me know and I will be happy to support.
Thanks
@chrisjamiecarter

2024-09-13 19:38 UTC, JvR-Hannes commented
@chrisjamiecarter I have changed the name as you requested. I'm still struggling a bit with the name changes afterwards and the pull requests etc.
I will do some more homework to improve on this matter and hope that in the future, it is either less or no mistakes like this.

Thank you @chrisjamiecarter

2024-09-13 20:21 UTC, chrisjamiecarter approved these changes
Hey @JvR-Hannes 👋 ,

Fantastic job on your another project submission 🎉

Thank you for persisting with correcting some mistakes early on! It makes my life as a reviewer easier 😄 

I have added some minor comments that I feel can quickly support your growth as a developer.

And I have a few suggestions that I believe could help you enhance this application even further:

- You could clear the console each time before you write the menu. This would allow the user to segment an action, maintain readability of the console window and improve the experience for the user.
- If you present a list of information, like the habits, implement a `Console.WriteLine("Press any key to continue...");` and a `Console.Read();` after you have displayed the data. This will allow the user to read and digest the list before going back to a clean main menu (previous point).

**Bugs**
Unfortunately, I did spot a bug within your application:

As you can see, I have records in the database:
![image](https://github.com/user-attachments/assets/85124fec-34ce-4574-aaa7-f3a6c1cf17b0)

But when I View by Date Range, I get no records found:
![image](https://github.com/user-attachments/assets/5332ecc3-bc20-484c-a33f-6da2a2519beb)

I suggest revisiting to try understand and fix any issues, but as these relate to the extra challenge requirement they will not block the PR.

Feel free to reach out if you have any questions or if you'd like to collaborate further on any of these points.

I will go ahead and mark as approved, keep up the excellent work on the next projects! 😊

Best regards,
@chrisjamiecarter

2024-09-13 20:21 UTC, chrisjamiecarter commented on Habit-Tracker-JVR-Hannes/Habit-Tracker/Program.cs
> +                checkCmd.CommandText = $"SELECT EXISTS(SELECT 1 FROM habits WHERE Id = {recordId})";
Would love to see you parameterise all of your queries like you have done elsewhere in your code.

Although, the ones I have seen are fine as you are validating user input and dealing with `int` and `DateTime`.

2024-09-13 20:21 UTC, chrisjamiecarter commented on Habit-Tracker-JVR-Hannes/Habit-Tracker/Program.cs
> +
Remember you Spacing [code-conventions](https://thecsharpacademy.com/article/58/code-conventions)

- Remove empty lines after opening curly brackets and before closing curly brackets.

![image](https://github.com/user-attachments/assets/a8385d03-6bc4-46c9-8f3c-519f3e1bf9f4)

2024-09-13 20:21 UTC, chrisjamiecarter commented on Habit-Tracker-JVR-Hannes/Habit-Tracker/Properties/habit-Tracker.db
Ideally databases should not be stored in source control.

2024-09-13 20:21 UTC, chrisjamiecarter commented on Habit-Tracker-JVR-Hannes/Habit-Tracker/Properties/launchSettings.json
> +      "workingDirectory": "C:\\Users\\Hannes\\source\\repos\\Habit-Tracker\\Habit-Tracker\\Properties\\"
Be careful with hardcoding workingDirectory paths.

This path does not exist on my machine, so throws an exception on start-up.

If you are relying on this, add a useful not in your README under a Installation/Getting Started/Usage section.

2024-09-13 20:21 UTC, closed without merging