Submit for code review
TheCSharpAcademy/CodeReviews.Console.HabitTracker pull request #232
Opened 2024-12-05 18:57 UTC by Alvind0

Challenge requirements to be done in the next days.

2024-12-14 08:51 UTC, K-MYR requested changes
@Alvind0 **Thank you** for submitting your first console application using a real database and even including the challenges! :+1:
Unfortunately I ran into some bugs when deleting/updating a record, deleting a habit and viewing statistics.
If you have any questions about the source of the errors or you dont know how to fix them feel free to ask me here or on discord! :smile:

2024-12-14 08:51 UTC, K-MYR commented on Alvind0.HabitTracker/Database.cs
> +Date LIKE '%' || @month || '-%'";
This implementation causes records for the specified month of each year to be counted, not only records for "this month." For clarification, I added a record with the date 12-12-2012, and it is included even if the current month is December 2024.

2024-12-14 08:51 UTC, K-MYR commented on Alvind0.HabitTracker/Database.cs
> +    }
Code Convention: missing empty line

2024-12-14 13:24 UTC, Alvind0 commented
Thank you for the detailed review! I will fix it as soon as I can!

2024-12-25 18:50 UTC, TheCSharpAcademy commented
@Alvind0 I'm archiving this for Admin reasons, feel free to reopen when you're ready and we'll finish the review. @K-MYR you should get your points regardless. 🫡

2025-01-01 12:07 UTC, Alvind0 commented
@TheCSharpAcademy Hi, I fixed the bugs mentioned by @K-MYR but I don't seem to have the ability to reopen this PR. Can you reopen it for me?

2025-01-01 21:21 UTC, K-MYR commented
I reopened the PR for you! Good job, you fixed most of the issues!  👍 But i found one remaining bug 🤓  When trying to update   the habit type of a record i get the following error:
![image](https://github.com/user-attachments/assets/58946480-6d51-49ec-9191-91d40f007447)
When you commited your fix just re-request a review and i ll approve your PR! 🎉

2025-01-02 08:17 UTC, K-MYR approved these changes
Everything works now! 😄 
Congratulations! You finished your 3rd project of the C# Academy + challenges! 🎉

2025-01-02 13:46 UTC, closed without merging